// This file is used by Code Analysis to maintain SuppressMessage
// attributes that are applied to this project.
// Project-level suppressions either have no target or are given
// a specific target and scoped to a namespace, type, member, etc.

using System.Diagnostics.CodeAnalysis;

[assembly: SuppressMessage("Design", "CA1031:Keine allgemeinen Ausnahmetypen abfangen", Justification = "<Ausstehend>", Scope = "member", Target = "~M:JulianAndHisDates.JulianandhisdatesForm.ScreenToPicture(System.String)~System.String")]
[assembly: SuppressMessage("Microsoft.Globalization", "CA1303:Literale nicht als lokalisierte Parameter übergeben", MessageId = "System.Windows.Forms.Control.set_Text(System.String)", Scope = "member", Target = "JulianAndHisDates.AboutBoxForm.#.ctor()")]
[assembly: SuppressMessage("Microsoft.Globalization", "CA1303:Literale nicht als lokalisierte Parameter übergeben", MessageId = "System.Windows.Forms.Control.set_AccessibleDescription(System.String)", Scope = "member", Target = "JulianAndHisDates.AboutBoxForm.#InitializeComponent()")]
[assembly: SuppressMessage("Microsoft.Globalization", "CA1303:Literale nicht als lokalisierte Parameter übergeben", MessageId = "System.Windows.Forms.Control.set_AccessibleName(System.String)", Scope = "member", Target = "JulianAndHisDates.AboutBoxForm.#InitializeComponent()")]
[assembly: SuppressMessage("Microsoft.Globalization", "CA1303:Literale nicht als lokalisierte Parameter übergeben", MessageId = "System.Windows.Forms.ToolTip.SetToolTip(System.Windows.Forms.Control,System.String)", Scope = "member", Target = "JulianAndHisDates.AboutBoxForm.#InitializeComponent()")]
[assembly: SuppressMessage("Microsoft.Globalization", "CA1303:Literale nicht als lokalisierte Parameter übergeben", MessageId = "System.Windows.Forms.Control.set_Text(System.String)", Scope = "member", Target = "JulianAndHisDates.AboutBoxForm.#InitializeComponent()")]
[assembly: SuppressMessage("Microsoft.Globalization", "CA1303:Literale nicht als lokalisierte Parameter übergeben", MessageId = "System.Windows.Forms.Control.set_AccessibleDescription(System.String)", Scope = "member", Target = "JulianAndHisDates.JulianandhisdatesForm.#InitializeComponent()")]
[assembly: SuppressMessage("Microsoft.Globalization", "CA1303:Literale nicht als lokalisierte Parameter übergeben", MessageId = "System.Windows.Forms.Control.set_AccessibleName(System.String)", Scope = "member", Target = "JulianAndHisDates.JulianandhisdatesForm.#InitializeComponent()")]
[assembly: SuppressMessage("Microsoft.Globalization", "CA1303:Literale nicht als lokalisierte Parameter übergeben", MessageId = "System.Windows.Forms.Control.set_Text(System.String)", Scope = "member", Target = "JulianAndHisDates.JulianandhisdatesForm.#InitializeComponent()")]
[assembly: SuppressMessage("Microsoft.Globalization", "CA1303:Literale nicht als lokalisierte Parameter übergeben", MessageId = "System.Windows.Forms.ToolTip.SetToolTip(System.Windows.Forms.Control,System.String)", Scope = "member", Target = "JulianAndHisDates.JulianandhisdatesForm.#InitializeComponent()")]
[assembly: SuppressMessage("Microsoft.Globalization", "CA1303:Literale nicht als lokalisierte Parameter übergeben", MessageId = "System.Windows.Forms.NotifyIcon.set_Text(System.String)", Scope = "member", Target = "JulianAndHisDates.JulianandhisdatesForm.#InitializeComponent()")]
[assembly: SuppressMessage("Microsoft.Mobility", "CA1601:DoNotUseTimersThatPreventPowerStateChanges", Scope = "member", Target = "JulianAndHisDates.JulianandhisdatesForm.#InitializeComponent()")]
[assembly: SuppressMessage("Microsoft.Globalization", "CA1303:Literale nicht als lokalisierte Parameter übergeben", MessageId = "System.Windows.Forms.ToolStripItem.set_AccessibleDescription(System.String)", Scope = "member", Target = "JulianAndHisDates.JulianandhisdatesForm.#InitializeComponent()")]
[assembly: SuppressMessage("Microsoft.Globalization", "CA1303:Literale nicht als lokalisierte Parameter übergeben", MessageId = "System.Windows.Forms.ToolStripItem.set_AccessibleName(System.String)", Scope = "member", Target = "JulianAndHisDates.JulianandhisdatesForm.#InitializeComponent()")]
[assembly: SuppressMessage("Microsoft.Globalization", "CA1303:Literale nicht als lokalisierte Parameter übergeben", MessageId = "System.Windows.Forms.ToolStripItem.set_Text(System.String)", Scope = "member", Target = "JulianAndHisDates.JulianandhisdatesForm.#InitializeComponent()")]
[assembly: SuppressMessage("Microsoft.Globalization", "CA1303:Literale nicht als lokalisierte Parameter übergeben", MessageId = "System.Windows.Forms.ToolStripItem.set_ToolTipText(System.String)", Scope = "member", Target = "JulianAndHisDates.JulianandhisdatesForm.#InitializeComponent()")]
[assembly: SuppressMessage("Microsoft.Globalization", "CA1303:Literale nicht als lokalisierte Parameter übergeben", MessageId = "System.Windows.Forms.Control.set_AccessibleDescription(System.String)", Scope = "member", Target = "JulianAndHisDates.JulianDateCalculatorForm.#InitializeComponent()")]
[assembly: SuppressMessage("Microsoft.Globalization", "CA1303:Literale nicht als lokalisierte Parameter übergeben", MessageId = "System.Windows.Forms.Control.set_AccessibleName(System.String)", Scope = "member", Target = "JulianAndHisDates.JulianDateCalculatorForm.#InitializeComponent()")]
[assembly: SuppressMessage("Microsoft.Globalization", "CA1303:Literale nicht als lokalisierte Parameter übergeben", MessageId = "System.Windows.Forms.Control.set_Text(System.String)", Scope = "member", Target = "JulianAndHisDates.JulianDateCalculatorForm.#InitializeComponent()")]
[assembly: SuppressMessage("Microsoft.Globalization", "CA1303:Literale nicht als lokalisierte Parameter übergeben", MessageId = "System.Windows.Forms.ToolTip.SetToolTip(System.Windows.Forms.Control,System.String)", Scope = "member", Target = "JulianAndHisDates.JulianDateCalculatorForm.#InitializeComponent()")]
[assembly: SuppressMessage("Microsoft.Globalization", "CA1303:Literale nicht als lokalisierte Parameter übergeben", MessageId = "System.Windows.Forms.ToolStripItem.set_AccessibleDescription(System.String)", Scope = "member", Target = "JulianAndHisDates.JulianDateCalculatorForm.#InitializeComponent()")]
[assembly: SuppressMessage("Microsoft.Globalization", "CA1303:Literale nicht als lokalisierte Parameter übergeben", MessageId = "System.Windows.Forms.ToolStripItem.set_AccessibleName(System.String)", Scope = "member", Target = "JulianAndHisDates.JulianDateCalculatorForm.#InitializeComponent()")]
[assembly: SuppressMessage("Microsoft.Globalization", "CA1303:Literale nicht als lokalisierte Parameter übergeben", MessageId = "System.Windows.Forms.ToolStripItem.set_Text(System.String)", Scope = "member", Target = "JulianAndHisDates.JulianDateCalculatorForm.#InitializeComponent()")]
[assembly: SuppressMessage("Microsoft.Globalization", "CA1303:Literale nicht als lokalisierte Parameter übergeben", MessageId = "System.Windows.Forms.ToolStripItem.set_ToolTipText(System.String)", Scope = "member", Target = "JulianAndHisDates.JulianDateCalculatorForm.#InitializeComponent()")]
[assembly: SuppressMessage("Microsoft.Globalization", "CA1303:Literale nicht als lokalisierte Parameter übergeben", MessageId = "System.Windows.Forms.Control.set_AccessibleDescription(System.String)", Scope = "member", Target = "JulianAndHisDates.JulianDateConverterForm.#InitializeComponent()")]
[assembly: SuppressMessage("Microsoft.Globalization", "CA1303:Literale nicht als lokalisierte Parameter übergeben", MessageId = "System.Windows.Forms.Control.set_AccessibleName(System.String)", Scope = "member", Target = "JulianAndHisDates.JulianDateConverterForm.#InitializeComponent()")]
[assembly: SuppressMessage("Microsoft.Globalization", "CA1303:Literale nicht als lokalisierte Parameter übergeben", MessageId = "System.Windows.Forms.Control.set_Text(System.String)", Scope = "member", Target = "JulianAndHisDates.JulianDateConverterForm.#InitializeComponent()")]
[assembly: SuppressMessage("Microsoft.Globalization", "CA1303:Literale nicht als lokalisierte Parameter übergeben", MessageId = "System.Windows.Forms.ToolStripItem.set_AccessibleDescription(System.String)", Scope = "member", Target = "JulianAndHisDates.JulianDateConverterForm.#InitializeComponent()")]
[assembly: SuppressMessage("Microsoft.Globalization", "CA1303:Literale nicht als lokalisierte Parameter übergeben", MessageId = "System.Windows.Forms.ToolStripItem.set_AccessibleName(System.String)", Scope = "member", Target = "JulianAndHisDates.JulianDateConverterForm.#InitializeComponent()")]
[assembly: SuppressMessage("Microsoft.Globalization", "CA1303:Literale nicht als lokalisierte Parameter übergeben", MessageId = "System.Windows.Forms.ToolStripItem.set_Text(System.String)", Scope = "member", Target = "JulianAndHisDates.JulianDateConverterForm.#InitializeComponent()")]
[assembly: SuppressMessage("Microsoft.Globalization", "CA1303:Literale nicht als lokalisierte Parameter übergeben", MessageId = "System.Windows.Forms.ToolStripItem.set_ToolTipText(System.String)", Scope = "member", Target = "JulianAndHisDates.JulianDateConverterForm.#InitializeComponent()")]
